instrument:
  name: CE01ISSM-MFD35-02-PRESFA000

harvest_config:
  refresh: true
  test: false

output:
  format: zarr # [NOT IMPLEMENTED]
  target:
    urlpath: s3://ooi-data

extra_attributes: {} # [NOT IMPLEMENTED]
