instrument:
  name: example

harvest_config:
  goldcopy: false
  refresh: true
  test: false

output:
  format: zarr # [NOT IMPLEMENTED]
  target:
    urlpath: s3://ooi-data

extra_attributes: {} # [NOT IMPLEMENTED]
