#!/usr/bin/env bash

set -e
set -x

# Ensure we are on the latest commit
# of the branch where we are converting
# recipes from. Currently this is `master`.
export CF_CURRENT_BRANCH="${GITHUB_REF/refs\/heads\//}"
git checkout "${CF_CURRENT_BRANCH}"

export PYTHONUNBUFFERED=1

# Install Miniconda.
echo ""
echo "Installing a fresh version of Miniconda."
curl -L https://repo.continuum.io/miniconda/Miniconda3-4.6.14-Linux-x86_64.sh > ~/miniconda.sh
bash ~/miniconda.sh -b -p ~/miniconda
touch ~/miniconda/conda-meta/pinned
(
    source ~/miniconda/bin/activate root

    # Configure conda.
    echo ""
    echo "Configuring conda."
    conda config --set show_channel_urls true
    conda config --set auto_update_conda false
    conda config --set add_pip_as_python_dependency false
    conda config --add channels conda-forge

    unset conda
    conda update -n root --yes --quiet conda
)
source ~/miniconda/bin/activate root

conda install --yes --quiet \
  git=2.12.2 \
  "gitpython>=3.0.8" \
  requests

conda info
conda config --get

set +x
mkdir -p ~/.ooi-harvester
set -x

echo "Current branch is ${CF_CURRENT_BRANCH}"
ls ~/.ooi-harvester